//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenVanDuoc_2210900016_Project2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class donhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public donhang()
        {
            this.chitietdonhangs = new HashSet<chitietdonhang>();
        }
        [Display(Name ="Mã đơn hàng")]
    
        public int MaDon { get; set; }
        [Display(Name = "Mã Khách")]
        public Nullable<int> Makhach { get; set; }
        [Display(Name = "Ngày đặt hàng")]
        public Nullable<System.DateTime> NgayDatHang { get; set; }
        [Display(Name = "Tổng giá trị")]
        public Nullable<decimal> TongGiaTri { get; set; }
        [Display(Name = "Thanh toán")]
        public Nullable<bool> ThanhToan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietdonhang> chitietdonhangs { get; set; }
        public virtual khachhang khachhang { get; set; }
    }
}
