//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenVanDuoc_2210900016_Project2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NvdAccount
    {
        [Display(Name ="ID")]
        public int NvdID { get; set; }
        [Display(Name ="Tài khoản")]
        public string NvdUserName { get; set; }
        [Display(Name = "Mật khẩu")]
        public string NvdPassWord { get; set; }
        [Display(Name = "Họ và tên")]
        public string NvdFullName { get; set; }
        [Display(Name = "Email")]
        public string NvdEmail { get; set; }
        [Display(Name = "Số điện thoại")]
        public string NvdPhone { get; set; }
        [Display(Name = "Active")]
        public Nullable<bool> NvdActive { get; set; }
    }
}
